/**
 * Generates src/data/worldMap.ts — the dot-matrix landmass for the hero route map.
 *
 * Rather than ship a geo library and 138 kB of GeoJSON to the browser, we sample
 * a lon/lat grid against Natural Earth's 110m land polygons here, at build time,
 * and emit a flat array of projected viewBox coordinates. The runtime only ever
 * sees integers.
 *
 *   node scripts/build-map.mjs
 *
 * Source: naturalearthdata.com, ne_110m_land (public domain).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

/**
 * The window is chosen to hold the whole China → Morocco lane with margin: far
 * enough west for the Atlantic behind Casablanca, far enough east for the East
 * China Sea, and far enough south for the Malacca dip at 2°N.
 *
 * The latitude band is deliberately tight. Every degree of empty ocean costs
 * the hero 10 units of height, and the band already renders at roughly 3.7:1 —
 * in a landscape viewport the map competes with the copy for vertical space, so
 * anything the lane does not actually pass through is trimmed. The 4° of slack
 * below Singapore is exactly enough to clear its two-line label.
 */
const WINDOW = { lonMin: -32, lonMax: 138, latMin: -2, latMax: 44 };
const UNITS_PER_DEG = 10;
const STEP = 1.2; // degrees between sampled dots
const DOT = 4; // side of each square, in map units

const W = (WINDOW.lonMax - WINDOW.lonMin) * UNITS_PER_DEG;
const H = (WINDOW.latMax - WINDOW.latMin) * UNITS_PER_DEG;

const projectX = (lon) => (lon - WINDOW.lonMin) * UNITS_PER_DEG;
const projectY = (lat) => (WINDOW.latMax - lat) * UNITS_PER_DEG;

// --- point in polygon ------------------------------------------------------

/** Ray casting. Even-odd across every ring, so interior holes fall out for free. */
function inRing(lon, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

function inPolygon(lon, lat, rings) {
  let inside = false;
  for (const ring of rings) if (inRing(lon, lat, ring)) inside = !inside;
  return inside;
}

// --- collect polygons, pre-filtered by bounding box ------------------------

const geo = JSON.parse(readFileSync(join(here, 'ne_110m_land.geojson'), 'utf8'));
const polygons = [];

for (const feature of geo.features) {
  const { type, coordinates } = feature.geometry;
  const parts = type === 'Polygon' ? [coordinates] : coordinates;
  for (const rings of parts) {
    let minLon = Infinity;
    let maxLon = -Infinity;
    let minLat = Infinity;
    let maxLat = -Infinity;
    for (const [lon, lat] of rings[0]) {
      if (lon < minLon) minLon = lon;
      if (lon > maxLon) maxLon = lon;
      if (lat < minLat) minLat = lat;
      if (lat > maxLat) maxLat = lat;
    }
    if (maxLon < WINDOW.lonMin || minLon > WINDOW.lonMax) continue;
    if (maxLat < WINDOW.latMin || minLat > WINDOW.latMax) continue;
    polygons.push({ rings, minLon, maxLon, minLat, maxLat });
  }
}

// --- sample ----------------------------------------------------------------

const dots = [];
for (let lat = WINDOW.latMin; lat <= WINDOW.latMax; lat += STEP) {
  for (let lon = WINDOW.lonMin; lon <= WINDOW.lonMax; lon += STEP) {
    let hit = false;
    for (const p of polygons) {
      if (lon < p.minLon || lon > p.maxLon || lat < p.minLat || lat > p.maxLat) continue;
      if (inPolygon(lon, lat, p.rings)) {
        hit = true;
        break;
      }
    }
    if (hit) dots.push(Math.round(projectX(lon)), Math.round(projectY(lat)));
  }
}

// --- emit ------------------------------------------------------------------

const out = `// GENERATED by scripts/build-map.mjs — do not edit by hand.
// Land dots sampled from Natural Earth 110m (public domain) on a ${STEP}° grid.

/** Equirectangular window and viewBox for the hero route map. */
export const MAP = {
  lonMin: ${WINDOW.lonMin},
  lonMax: ${WINDOW.lonMax},
  latMin: ${WINDOW.latMin},
  latMax: ${WINDOW.latMax},
  width: ${W},
  height: ${H},
} as const;

/** Project a real coordinate into the map's viewBox space. */
export function project(lon: number, lat: number): [number, number] {
  return [(lon - MAP.lonMin) * ${UNITS_PER_DEG}, (MAP.latMax - lat) * ${UNITS_PER_DEG}];
}

/** Side of one land square, in map units. Sized against the ${STEP}° sample grid. */
export const DOT = ${DOT};

/** Flat [x, y, x, y, …] pairs — ${dots.length / 2} land dots. */
export const LAND_DOTS: number[] = [${dots.join(',')}];
`;

writeFileSync(join(here, '..', 'src', 'data', 'worldMap.ts'), out);
console.log(`${dots.length / 2} dots · viewBox ${W}x${H} · ${(out.length / 1024).toFixed(1)} kB`);
